# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11VB4ewr_FuogLrsWftnjbRJKJ4MUpSPB
"""

"""
Configuration settings for Talent Match System
"""

# TGV Default Weights (from Step 1 Analysis)
DEFAULT_TGV_WEIGHTS = {
    "interpersonal_skills": 0.612,
    "leadership_competencies": 0.314,
    "execution_competencies": 0.041,
    "attention_processing": 0.016,
    "cognitive_ability": 0.009,
    "experience": 0.005,
    "work_preferences": 0.003
}

# Visualization Colors
COLORS = {
    "primary": "#1f77b4",
    "success": "#2ca02c",
    "warning": "#ff7f0e",
    "danger": "#d62728",
    "info": "#17becf"
}

# Match Rate Thresholds
THRESHOLDS = {
    "excellent": 80,
    "good": 70,
    "average": 60,
    "below_average": 50
}