# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11VB4ewr_FuogLrsWftnjbRJKJ4MUpSPB
"""

"""
LLM Integration for Job Profile Generation
Uses OpenRouter API (or any OpenAI-compatible endpoint)
"""

import requests
import streamlit as st
import json
from typing import Dict
import pandas as pd


def generate_job_profile(
    role_name: str,
    job_level: str,
    role_purpose: str,
    benchmark_employees: pd.DataFrame
) -> Dict[str, str]:
    """
    Generate job requirements, description, and competencies using LLM

    Args:
        role_name: Job title
        job_level: Job level (e.g., Middle, Senior)
        role_purpose: Brief description of role purpose
        benchmark_employees: DataFrame of benchmark employees (high performers)

    Returns:
        Dictionary with keys: 'requirements', 'description', 'competencies'
    """

    try:
        # Get API key from Streamlit secrets
        api_key = st.secrets.get("openrouter", {}).get("api_key")

        if not api_key:
            st.warning("OpenRouter API key not configured. Using fallback generation.")
            return generate_fallback_profile(role_name, job_level, role_purpose)

        # Prepare benchmark employee context
        benchmark_context = prepare_benchmark_context(benchmark_employees)

        # Construct prompt
        prompt = f"""You are an expert HR analyst and job description specialist. Based on the following information, generate a comprehensive job profile.

**Role Information:**
- Role Name: {role_name}
- Job Level: {job_level}
- Role Purpose: {role_purpose}

**Benchmark Employees (High Performers in similar roles):**
{benchmark_context}

**Task:**
Generate a professional job profile with these THREE sections:

1. **Job Requirements** (150-200 words):
   - Technical skills and qualifications needed
   - Educational background
   - Years of experience
   - Tools, technologies, or methods they should master
   - Analytical and problem-solving capabilities
   - Communication and collaboration requirements

2. **Job Description** (100-150 words):
   - What the person will do day-to-day
   - Key responsibilities
   - Impact and value they'll create
   - Who they'll work with
   - Balance between technical depth and business context

3. **Key Competencies** (List 8-12 items):
   - Specific technical competencies (e.g., "SQL: complex joins, CTEs, window functions")
   - Soft skills (e.g., "Stakeholder management across organizational levels")
   - Tools and technologies
   - Domain knowledge areas

**Output Format:**
Return ONLY a valid JSON object with this exact structure:
{{
  "requirements": "...",
  "description": "...",
  "competencies": ["item1", "item2", ...]
}}

**Important:**
- Be specific and actionable
- Focus on {role_name} role at {job_level} level
- Make it realistic for the given job level
- Use professional, clear language
- NO markdown formatting in the JSON values
- Return ONLY the JSON, no additional text"""

        # Call OpenRouter API
        response = requests.post(
            url="https://openrouter.ai/api/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json"
            },
            json={
                "model": "meta-llama/llama-3.1-8b-instruct:free",  # Free model
                "messages": [
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                "temperature": 0.7,
                "max_tokens": 1500
            },
            timeout=30
        )

        response.raise_for_status()

        # Parse response
        result = response.json()
        content = result['choices'][0]['message']['content']

        # Clean and parse JSON
        content = content.strip()
        if content.startswith("```json"):
            content = content[7:]
        if content.startswith("```"):
            content = content[3:]
        if content.endswith("```"):
            content = content[:-3]
        content = content.strip()

        profile = json.loads(content)

        # Validate structure
        required_keys = ['requirements', 'description', 'competencies']
        if not all(key in profile for key in required_keys):
            st.warning("LLM response missing required fields. Using fallback.")
            return generate_fallback_profile(role_name, job_level, role_purpose)

        return profile

    except requests.exceptions.RequestException as e:
        st.warning(f"API request failed: {e}. Using fallback generation.")
        return generate_fallback_profile(role_name, job_level, role_purpose)

    except json.JSONDecodeError as e:
        st.warning(f"Failed to parse LLM response: {e}. Using fallback generation.")
        return generate_fallback_profile(role_name, job_level, role_purpose)

    except Exception as e:
        st.warning(f"Unexpected error: {e}. Using fallback generation.")
        return generate_fallback_profile(role_name, job_level, role_purpose)


def prepare_benchmark_context(benchmark_df: pd.DataFrame) -> str:
    """Prepare benchmark employee context for LLM prompt"""

    if benchmark_df.empty:
        return "No benchmark employees provided."

    context_lines = []
    for idx, row in benchmark_df.iterrows():
        line = f"- {row.get('fullname', 'N/A')} | Position: {row.get('position', 'N/A')} | Directorate: {row.get('directorate', 'N/A')}"
        context_lines.append(line)

    return "\n".join(context_lines)


def generate_fallback_profile(role_name: str, job_level: str, role_purpose: str) -> Dict[str, str]:
    """Generate a basic job profile without LLM (fallback)"""

    # Template-based generation
    level_requirements = {
        "Entry": "1-2 years of experience, bachelor's degree",
        "Junior": "2-3 years of experience, bachelor's degree",
        "Middle": "3-5 years of experience, bachelor's or master's degree",
        "Senior": "5-7 years of experience, bachelor's or master's degree",
        "Lead": "7-10 years of experience, proven leadership track record",
        "Manager": "8+ years of experience, team management experience",
        "Director": "10+ years of experience, strategic leadership experience"
    }

    exp_requirement = level_requirements.get(job_level, "Relevant experience")

    requirements = f"""**{role_name}** ({job_level} Level)

{role_purpose}

**Requirements:**
- {exp_requirement} in related field
- Strong analytical and problem-solving skills
- Proficiency in relevant tools and technologies
- Excellent communication and collaboration abilities
- Proven track record of delivering results
- Ability to work independently and in teams
- Continuous learning mindset
- Stakeholder management skills"""

    description = f"""As a {role_name} at the {job_level} level, you will {role_purpose.lower()}

You'll work closely with cross-functional teams to analyze data, generate insights, and drive business decisions. This role requires balancing technical depth with business acumen, translating complex findings into actionable recommendations.

You'll own projects end-to-end, from understanding stakeholder needs to delivering polished outputs that influence strategy and operations."""

    competencies = [
        f"{role_name.split()[0]} expertise and domain knowledge",
        "Data analysis and statistical thinking",
        "Technical proficiency in relevant tools",
        "Problem-solving and critical thinking",
        "Communication and storytelling",
        "Project management and prioritization",
        "Stakeholder engagement",
        "Continuous improvement mindset",
        "Collaboration and teamwork",
        "Business acumen and strategic thinking"
    ]

    return {
        "requirements": requirements,
        "description": description,
        "competencies": competencies
    }


# Alternative: Use free Claude API (if available)
def generate_job_profile_claude(
    role_name: str,
    job_level: str,
    role_purpose: str,
    benchmark_employees: pd.DataFrame
) -> Dict[str, str]:
    """
    Alternative implementation using Claude API
    Can be used if you have Anthropic API access
    """

    # Similar implementation to above, but using Anthropic's API
    # This is a placeholder for demonstration

    return generate_fallback_profile(role_name, job_level, role_purpose)